# Generated by Django 5.0.6 on 2024-06-02 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelexample',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
