# Generated by Django 5.0.6 on 2024-06-02 09:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0003_modelexample_prices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificateNumber', models.CharField(max_length=100)),
                ('issueDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('validUntil', models.DateTimeField()),
                ('exampleCertificate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exampleCertificate', to='djangoapp.modelexample')),
            ],
        ),
        migrations.CreateModel(
            name='ExampleReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('commet', models.TextField()),
                ('data_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('exampleForeignKey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exampleReviews', to='djangoapp.modelexample')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExampleStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('exampleVarieties', models.ManyToManyField(related_name='exampleStores', to='djangoapp.modelexample')),
            ],
        ),
    ]
